### ISSUE TITLE
the image of arrow is no-exist

### ISSUE THREAD

**Issue by cleveng** [ronffy/wepy-com-calendar#4]
# filename: wepy-com-calendar.wpy 
# line: 387

`code: <image wx:if="{{item.checked}}" class="icon-checked" mode="widthFix" src="{{icon || 'http://oxk008h6r.bkt.clouddn.com/check-' + (theme === 'default' ? 'black' : theme) + '.png'}}" />`

-------------
http://oxk008h6r.bkt.clouddn.com  is Unavailable。。

Lucky, i can set the icon value  to fix it....

by the way, pls you fix it...

**Comment by ronffy** [comment]
Fixed and thanks! 👍
