### ISSUE TITLE
后台获取打卡的日期后，更新check的数据，没有作用呢？

### ISSUE THREAD

**Issue by omeletteWithEgg** [ronffy/wepy-com-calendar#5]
后台获取打卡的日期后，更新check的数据，为什么不起作用呢？已经使用this.$apply()了，还是不生效。静态写死的数据就正常。

**Comment by ronffy** [comment]
更新的字段是`checks`，而非`check`。
如果不是这个问题，你这样提问我帮不上你的，可以发一个简单的示例demo链接。
